import ScrollView from '@/app/components/scrollView';
import { Metadata } from 'next';

interface LayoutProps {
  headers: React.ReactNode;
  history: React.ReactNode;
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: 'Deklarasjoner | FAA',
  description: 'Generated by create next app',
};

export default function Layout({ headers, history, children }: LayoutProps) {
  return (
    <ScrollView width={1400} className={'p-5'}>
      {history}

      {headers}

      {children}
    </ScrollView>
  );
}
