export type AdrKlasser =
  | 'BrannfarligeVaesker'
  | 'RadioaktivtMateriale'
  | 'EtsendeStoffer'
  | 'ForskjelligeFarligeStofferOgGjenstander'
  | 'MiljoefarligeStoffer'
  | 'BrannfarligeGasser'
  | 'IkkeBrannfarligeGasserIkkeGiftigeGasser'
  | 'GiftigeGasser'
  | 'BrannfarligeFasteStofferOgAndre'
  | 'SelvantennendeStoffer'
  | 'StofferSomUtviklerBrennbareGasserIKontaktMedVann'
  | 'OksiderendeStoffer'
  | 'OrganiskePeroksider'
  | 'GiftigeStoffer'
  | 'ForskjelligeFarligeStofferOgGjenstanderBatterier';
